-- Create competencies table
CREATE TABLE IF NOT EXISTS competencies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create candidato_competencias table
CREATE TABLE IF NOT EXISTS candidato_competencias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  candidato_id INT NOT NULL,
  competencia_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (candidato_id) REFERENCES candidate_profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (competencia_id) REFERENCES competencies(id) ON DELETE CASCADE,
  UNIQUE KEY unique_candidato_competencia (candidato_id, competencia_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert initial competencies
INSERT INTO competencies (nome) VALUES
('Comunicação'),
('Comunicação verbal'),
('Comunicação escrita'),
('Boa comunicação'),
('Escuta ativa'),
('Inteligência emocional'),
('Liderança'),
('Trabalho em equipe'),
('Gestão de conflitos'),
('Organização'),
('Proatividade'),
('Resiliência'),
('Adaptabilidade'),
('Criatividade'),
('Pensamento analítico'),
('Pensamento crítico'),
('Gestão de tempo'),
('Gestão de prioridades'),
('Negociação'),
('Persuasão'),
('Storytelling'),
('Relacionamento interpessoal'),
('Senso de urgência'),
('Empatia'),
('Ownership'),
('Perfil Hunter'),
('Perfil Farmer'),
('Perfil consultivo'),
('Visão estratégica'),
('Foco em resultados'),
('Orientação a resultados'),
('Resolução de problemas'),
('Capacidade analítica'),
('Tomada de decisão'),
('Flexibilidade'),
('Aprendizado contínuo'),
('Colaboração'),
('Comprometimento'),
('Responsabilidade'),
('Autogestão'),
('Trabalho sob pressão'),
('Capacidade de adaptação'),
('Gestão de pessoas'),
('Gestão de equipes'),
('Motivação'),
('Planejamento'),
('Planejamento estratégico'),
('Atendimento ao cliente'),
('Perfil executor'),
('Perfil analítico'),
('Perfil comunicativo'),
('Perfil comercial'),
('Perfil negociador'),
('Gestão de crise'),
('Facilidade de aprendizado'),
('Alta performance'),
('Multitarefas'),
('Visão de negócio'),
('Capacidade de inovação'),
('Inteligência comercial'),
('Relacionamento com clientes'),
('Cultura de feedback'),
('Perfil competitivo'),
('Perfil estratégico'),
('Perfil operacional'),
('Perfil processual'),
('Perfil disciplinado'),
('Perfil organizado'),
('Perfil influenciador'),
('Perfil persuasivo'),
('Perfil relacional'),
('Perfil técnico'),
('Perfil resiliente'),
('Perfil dinâmico'),
('Perfil detalhista'),
('Perfil colaborativo'),
('Perfil independente'),
('Perfil autônomo'),
('Autonomia'),
('Senso de dono'),
('Espírito empreendedor'),
('Mentalidade comercial'),
('Capacidade de execução'),
('Capacidade de liderança'),
('Capacidade de influência'),
('Capacidade de argumentação'),
('Capacidade de convencimento'),
('Capacidade de aprendizado rápido'),
('Perfil externo'),
('Perfil interno'),
('Perfil híbrido'),
('Perfil corporativo'),
('Perfil hands-on'),
('Comunicação assertiva'),
('Comunicação consultiva'),
('Facilidade em networking'),
('Facilidade em apresentações'),
('Facilidade em vendas'),
('Perfil orientado a metas'),
('Perfil orientado a performance')
ON DUPLICATE KEY UPDATE nome=nome;
